-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES*PRICE) TOTAL_SALES
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;