-- 코드를 작성해주세요
SELECT
    THR_CHILD.ID
FROM ECOLI_DATA THR_CHILD
JOIN
(SELECT
    SEC_CHILD.ID
FROM ECOLI_DATA SEC_CHILD
JOIN
(SELECT
    ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL) PARENT
ON PARENT.ID = SEC_CHILD.PARENT_ID) SUB
ON SUB.ID = THR_CHILD.PARENT_ID;