-- 코드를 작성해주세요
SELECT
    DATA.ID
    , COALESCE(SUB.COUNT,0) CHILD_COUNT
FROM ECOLI_DATA DATA
LEFT JOIN
(SELECT
    PARENT_ID
    , COUNT(PARENT_ID) COUNT
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID) SUB
ON DATA.ID = SUB.PARENT_ID
ORDER BY DATA.ID ASC;