-- 코드를 입력하세요
SELECT
    P.PRODUCT_CODE
    , OS.SALES_AMOUNT*P.PRICE SALES
FROM PRODUCT P JOIN 
    (SELECT 
        PRODUCT_ID
        , SUM(SALES_AMOUNT) SALES_AMOUNT
     FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) OS ON P.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;
# GROUP BY P.PRODUCT_ID;

# (SELECT 
#         PRODUCT_ID
#         , SUM(SALES_AMOUNT) SALES_AMOUNT
#      FROM OFFLINE_SALE
#     GROUP BY PRODUCT_ID) ;