-- 코드를 입력하세요
# SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '세단' AND DURATION_TYPE = '30일 이상';


SELECT
    CAR_ID,
    CAR_TYPE,
    ROUND(FEE*(1-RATE/100)) FEE
FROM
    (SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        CASE
        WHEN C.CAR_TYPE = '세단' THEN ROUND(C.DAILY_FEE*30)
        WHEN C.CAR_TYPE = 'SUV' THEN ROUND(C.DAILY_FEE*30)
        END AS FEE,
        H.START_DATE,
        H.END_DATE,
        P.RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    LEFT JOIN (SELECT CAST(DISCOUNT_RATE AS SIGNED) RATE, CAR_TYPE
               FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
               WHERE DURATION_TYPE = '30일 이상') P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01')
    GROUP BY C.CAR_ID) T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;




# SELECT
#     CAR_ID,
#     CAR_TYPE,
#     FEE
# FROM
#     (SELECT
#         C.CAR_ID,
#         C.CAR_TYPE,
#         C.DAILY_FEE,
#         CASE
#         WHEN C.CAR_TYPE = '세단' THEN ROUND(C.DAILY_FEE*30*0.9)
#         WHEN C.CAR_TYPE = 'SUV' THEN ROUND(C.DAILY_FEE*30*0.92)
#         END AS FEE,
#         H.START_DATE,
#         H.END_DATE
#     FROM CAR_RENTAL_COMPANY_CAR C
#     LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     WHERE C.CAR_TYPE IN ('세단', 'SUV')
#     AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                          WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-01')
#     GROUP BY C.CAR_ID) T
# WHERE FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;



# SELECT
#     T.CAR_ID,
#     T.CAR_TYPE,
#     T.FEE
# FROM
#     (SELECT
#         C.CAR_ID,
#         C.CAR_TYPE,
#         CASE
#         WHEN C.CAR_TYPE = '세단' THEN ROUND(C.DAILY_FEE*30*0.9)
#         WHEN C.CAR_TYPE = 'SUV' THEN ROUND(C.DAILY_FEE*30*0.92)
#         END AS FEE,
#         H.START_DATE,
#         H.END_DATE
#     FROM CAR_RENTAL_COMPANY_CAR C
#     LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
#     WHERE C.CAR_TYPE IN ('SUV', '세단')
#     AND
#         (DATE_FORMAT(END_DATE, '%Y-%m-%d') < '2022-11-01'
#         OR DATE_FORMAT(START_DATE, '%Y-%m-%d') > '2022-11-30'
#         OR START_DATE IS NULL)
#     GROUP BY C.CAR_ID) T
# WHERE FEE >= 500000 AND FEE < 2000000
# ORDER BY T.FEE DESC, T.CAR_TYPE, T.CAR_ID DESC;



# SELECT
#     T.CAR_ID,
#     T.CAR_TYPE,
#     T.FEE
# FROM
#     (SELECT
#         C.CAR_ID,
#         C.CAR_TYPE,
#         CASE
#         WHEN C.CAR_TYPE = '세단' THEN ROUND(C.DAILY_FEE*30*(1-10/100))
#         WHEN C.CAR_TYPE = 'SUV' THEN ROUND(C.DAILY_FEE*30*(1-8/100))
#         END AS FEE,
#         H.START_DATE,
#         H.END_DATE
#     FROM CAR_RENTAL_COMPANY_CAR C
#     LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
#     WHERE C.CAR_TYPE IN ('SUV', '세단')
#     AND
#         (DATE_FORMAT(END_DATE, '%Y-%m-%d') < '2022-11-01'
#         OR DATE_FORMAT(START_DATE, '%Y-%m-%d') > '2022-11-30'
#         OR START_DATE IS NULL)
#     GROUP BY C.CAR_ID) T
# WHERE FEE >= 500000 AND FEE < 2000000
# ORDER BY T.FEE DESC, T.CAR_TYPE, T.CAR_ID DESC;