-- 코드를 입력하세요
-- WITH DATESORTED AS (
-- SELECT
--     C.CAR_ID
--     , C.CAR_TYPE
--     , CASE
--         WHEN C.CAR_TYPE = '세단' THEN C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)
--         ELSE C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)
--       END AS FEE
--     , H.START_DATE
--     , H.END_DATE
-- FROM CAR_RENTAL_COMPANY_CAR C
-- JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
-- JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
-- WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
--         AND P.DURATION_TYPE = '30일 이상'
--         AND (EXTRACT(MONTH FROM END_DATE) = 11
--              OR EXTRACT(MONTH FROM START_DATE) = 11
--              OR TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE)

-- )

WITH P AS (
SELECT
    CAR_TYPE
    , (100-DISCOUNT_RATE)/100 DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '30일 이상'
), H AS (
SELECT
    CAR_ID
    , START_DATE
    , END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE EXTRACT(MONTH FROM END_DATE) = 11
             OR EXTRACT(MONTH FROM START_DATE) = 11
             OR TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
), C AS (
SELECT
    CAR_ID
    , CAR_TYPE
    , DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV'
)

SELECT
    C.CAR_ID
    , C.CAR_TYPE
    , C.DAILY_FEE*30*P.DISCOUNT_RATE FEE
FROM C
JOIN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.DAILY_FEE*30*P.DISCOUNT_RATE) >= 500000 AND (C.DAILY_FEE*30*P.DISCOUNT_RATE) < 2000000
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM H)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;