-- 코드를 입력하세요
SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR C
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01')
AND (ROUND(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE/100)) >= 500000
AND ROUND(C.DAILY_FEE*30*(1-P.DISCOUNT_RATE/100)) < 2000000)
GROUP BY C.CAR_ID
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;