-- 코드를 작성해주세요
WITH COUNT AS (
SELECT
    ID
    , RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) 'RANK'
    , COUNT(ID) OVER() COUNT
FROM ECOLI_DATA
)
SELECT
    DATA.ID
    , CASE
        WHEN COUNT.COUNT*0.25 >= COUNT.RANK THEN 'CRITICAL'
        WHEN COUNT.COUNT*0.5 >= COUNT.RANK THEN 'HIGH'
        WHEN COUNT.COUNT*0.75 >= COUNT.RANK THEN 'MEDIUM'
        ELSE 'LOW'
        END AS COLONY_NAME
FROM ECOLI_DATA DATA
LEFT JOIN COUNT ON DATA.ID = COUNT.ID
ORDER BY ID
;