-- 코드를 입력하세요
SELECT
    U.USER_ID
    , U.NICKNAME
    , CONCAT(
        U.CITY, ' '
        , U.STREET_ADDRESS1, ' '
        , U.STREET_ADDRESS2
    ) 전체주소
    , CONCAT(
        LEFT(U.TLNO, 3), '-'
        , MID(U.TLNO, 4, 4), '-'
        , RIGHT(U.TLNO, 4)
    ) 전화번호
FROM USED_GOODS_USER U
JOIN
(SELECT
    WRITER_ID
    , COUNT(WRITER_ID) CNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3) B
ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC
;
