-- 코드를 입력하세요
SELECT
    ANIMAL_ID
    , NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN
(SELECT
    OUTS.ANIMAL_ID
FROM ANIMAL_OUTS OUTS
JOIN ANIMAL_INS INS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID)
ORDER BY ANIMAL_ID;
