-- 코드를 입력하세요
SELECT
    YEAR(SALE.SALES_DATE) YEAR
    , MONTH(SALE.SALES_DATE) MONTH
    , COUNT(DISTINCT INFO.USER_ID) PUCHASED_USERS
    , ROUND(COUNT(DISTINCT INFO.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO INFO
JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH
;

# SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021;