-- 코드를 작성해주세요
WITH Q AS (
SELECT
    EXTRACT(QUARTER FROM DIFFERENTIATION_DATE) QUARTER
    , COUNT(*) ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY EXTRACT(QUARTER FROM DIFFERENTIATION_DATE)
)

SELECT
    CONCAT(QUARTER, 'Q') QUARTER
    , ECOLI_COUNT
FROM Q
ORDER BY QUARTER
;