-- 코드를 입력하세요
SELECT
    NAME
    , DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN
(SELECT
    INS.ANIMAL_ID
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3
;