-- 코드를 입력하세요
SELECT SUB.NAME, SUB.DATETIME
FROM
(
SELECT I.NAME, I.DATETIME, RANK() OVER(ORDER BY I.DATETIME) "RANK"
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME
) SUB
WHERE RANK <=3;