-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME,
SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05-%'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;