-- 코드를 입력하세요
SELECT
 H.HISTORY_ID
 , ROUND(C.DAILY_FEE*DUE*((100-IFNULL(P.DISCOUNT_RATE, 0))/100),0) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN
(SELECT
    HISTORY_ID
    , CAR_ID
    , DATEDIFF(END_DATE, START_DATE)+1 DUE
    , CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE '무'
    END AS 'USE_DATE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON H.USE_DATE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
;