-- 코드를 입력하세요
WITH CAL AS (SELECT
    H.HISTORY_ID
    , DATEDIFF(H.END_DATE, H.START_DATE)+1 USE_DATE
    , CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN (SELECT ROUND(C.DAILY_FEE*(1-(DISCOUNT_RATE/100)),0) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90일%')
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN (SELECT ROUND(C.DAILY_FEE*(1-(DISCOUNT_RATE/100)),0) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30일%')
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN (SELECT ROUND(C.DAILY_FEE*(1-(DISCOUNT_RATE/100)), 0) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7일%')
        ELSE C.DAILY_FEE
    END AS DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
)
SELECT
    HISTORY_ID
    , USE_DATE*DAILY_FEE FEE
FROM CAL
ORDER BY FEE DESC, HISTORY_ID DESC;