-- 코드를 입력하세요
SELECT
    H.HISTORY_ID
    , CASE
        WHEN DATE < 7 THEN C.DAILY_FEE*DATE
        ELSE ROUND(C.DAILY_FEE*DATE*((100-P.DISCOUNT_RATE)/100),0)
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN
(SELECT
    HISTORY_ID
    , CAR_ID
    , DATEDIFF(END_DATE, START_DATE)+1 DATE
    , CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE '무'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
;