-- 코드를 입력하세요
SELECT
    SUB.FLAVOR
FROM
(SELECT
    H.FLAVOR
    , SUM(H.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF H
LEFT JOIN JULY J ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY) SUB;