-- 코드를 작성해주세요
WITH FRONT AS (
    SELECT
        CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT
    DISTINCT D.ID
    , D.EMAIL
    , D.FIRST_NAME
    , D.LAST_NAME
FROM DEVELOPERS D
JOIN FRONT F ON D.SKILL_CODE & F.CODE = F.CODE
ORDER BY D.ID
;