-- 코드를 작성해주세요
SELECT
    T.EMP_NO,
    T.EMP_NAME,
    T.GRADE,
    CASE
        WHEN T.GRADE = "S" THEN T.SAL*0.2
        WHEN T.GRADE = "A" THEN T.SAL*0.15
        WHEN T.GRADE = "B" THEN T.SAL*0.1
        ELSE T.SAL*0
    END AS BONUS
FROM
(SELECT
    E.EMP_NO,
    E.EMP_NAME,
    E.SAL,
    CASE
        WHEN SUM(G.SCORE)/2 >= 96 THEN "S"
        WHEN SUM(G.SCORE)/2 >= 90 THEN "A"
        WHEN SUM(G.SCORE)/2 >= 80 THEN "B"
        ELSE "C"
        END AS GRADE
FROM HR_EMPLOYEES E
LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL) T
ORDER BY T.EMP_NO;