-- 코드를 입력하세요
WITH CNT AS(
SELECT
    MEMBER_ID,
    COUNT(*) COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
), MAX_CNT AS(
SELECT
    MEMBER_ID,
    COUNT
FROM CNT
WHERE COUNT = (SELECT MAX(COUNT) FROM CNT))

SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_CNT)
ORDER BY REVIEW_DATE, REVIEW_TEXT;