-- 코드를 입력하세요
SELECT
    MONTH(START_DATE) MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY CASE MONTH(START_DATE)
            WHEN 8 THEN 1
            WHEN 9 THEN 2
            WHEN 10 THEN 3
         END, CAR_ID DESC;


# SELECT
#     MONTH(O.START_DATE) MONTH,
#     O.CAR_ID,
#     COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY O
# LEFT JOIN 
# (SELECT
#     CAR_ID,
#     COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY CAR_ID) T
# ON O.CAR_ID = T.CAR_ID
# WHERE RECORDS >= 5
# GROUP BY CAR_ID, MONTH(START_DATE);


# SELECT
#     MONTH(START_DATE) MONTH,
#     CAR_ID,
#     COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY CAR_ID, MONTH(START_DATE)
# ORDER BY CASE MONTH(START_DATE)
#             WHEN 8 THEN 1
#             WHEN 9 THEN 2
#             WHEN 10 THEN 3
#          END, CAR_ID DESC;


# SELECT
#     DATE_FORMAT(START_DATE, '%c') MONTH,
#     CAR_ID,
#     COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY CAR_ID, DATE_FORMAT(START_DATE, '%c')