-- 코드를 작성해주세요
WITH MAX_SIZE AS (
SELECT
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) YEAR
    , MAX(SIZE_OF_COLONY) MAX
FROM ECOLI_DATA
GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)
SELECT
    EXTRACT(YEAR FROM DATA.DIFFERENTIATION_DATE) YEAR
    , ((SELECT MAX FROM MAX_SIZE WHERE EXTRACT(YEAR FROM DATA.DIFFERENTIATION_DATE) = YEAR)-DATA.SIZE_OF_COLONY) YEAR_DEV
    , DATA.ID
FROM ECOLI_DATA DATA
ORDER BY YEAR, YEAR_DEV
;