-- 코드를 작성해주세요
SELECT
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) YEAR
    , MAX(SIZE_OF_COLONY) OVER(PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) - SIZE_OF_COLONY YEAR_DEV
    , ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV
;