-- 코드를 작성해주세요
SELECT
    INFO.ID
    , SUB.FISH_NAME
    , SUB.LENGTH
FROM FISH_INFO INFO
JOIN 
(SELECT
    I.FISH_TYPE
    , FISH_NAME
    , MAX(LENGTH) LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY I.FISH_TYPE, FISH_NAME) SUB
ON INFO.FISH_TYPE = SUB.FISH_TYPE AND INFO.LENGTH = SUB.LENGTH
ORDER BY ID
;