-- 코드를 작성해주세요
WITH MERGE AS(
SELECT
    SUM(G.SCORE) SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
WHERE YEAR = 2022
GROUP BY EMP_NO)


SELECT * FROM MERGE
WHERE SCORE = (SELECT MAX(SCORE) FROM MERGE);