-- 코드를 입력하세요

-- SELECT BOARD_ID, MAX(VIEWS) VIEWS FROM USED_GOODS_BOARD
-- GROUP BY BOARD_ID
-- ORDER BY VIEWS DESC;

SELECT '/home/grep/src/' || F.BOARD_ID || '/' || F.FILE_ID || F.FILE_NAME
|| F.FILE_EXT FILE_PATH
FROM USED_GOODS_FILE F
JOIN USED_GOODS_BOARD B
ON F.BOARD_ID = B.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;