-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', CONCAT(B.BOARD_ID, CONCAT('/', CONCAT(FILE_ID, CONCAT(FILE_NAME,FILE_EXT))))) FILE_PATH
FROM USED_GOODS_FILE F
JOIN 
(SELECT
    BOARD_ID
FROM USED_GOODS_BOARD
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)) B ON B.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC
;