-- 코드를 작성해주세요
SELECT
    SUB.FISH_COUNT
    , SUB.MAX_LENGTH
    , SUB.FISH_TYPE
FROM (
SELECT
    COUNT(ID) FISH_COUNT
    , MAX(LENGTH) MAX_LENGTH
    , AVG(COALESCE(LENGTH,10)) AVG
    , FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
) SUB
WHERE SUB.AVG >= 33
ORDER BY SUB.FISH_TYPE ASC
;