-- 코드를 작성해주세요
WITH FE AS(
SELECT SUM(CODE) CODE
FROM SKILLCODES
WHERE CATEGORY = "Front End"
), P AS(
SELECT CODE
FROM SKILLCODES
WHERE NAME = "Python"
), C AS(
SELECT CODE
FROM SKILLCODES
WHERE NAME = "C#")


SELECT
    CASE
        WHEN SKILL_CODE & (SELECT CODE FROM P) AND SKILL_CODE & (SELECT CODE FROM FE) THEN "A"
        WHEN SKILL_CODE & (SELECT CODE FROM C) THEN "B"
        WHEN SKILL_CODE & (SELECT CODE FROM FE) THEN "C"
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;